---
- name: verify app server is running or not
  shell: if ps -eaf | grep 'httpd' | grep -v grep > /dev/null; then echo 'process_running'; else echo'process_not_running'; fi
  ignore_errors: true
  register: app_proc_check
- debug: 
    msg: "{{ app_proc_check.stdout }}"
   
